/** Node constructors bundled into this web client. Native node types remain dynamically registered strings. */
export const enum node_type_e {
  application_settings = "application_settings",
  vec2 = "vec2",
  rect = "rect",
  math_f64 = "math_f64",
  math_vec2 = "math_vec2",
  lerp_f64 = "lerp_f64",
  lerp_vec2 = "lerp_vec2",
  lerp_rect = "lerp_rect",
  easing_f64 = "easing_f64",
  clamp_f64 = "clamp_f64",
  clamp_vec2 = "clamp_vec2",
  clamp_rect = "clamp_rect",
  screen_output = "screen_output",
  decklink_input = "decklink_input",
  decklink_output = "decklink_output",
  ndi_input = "ndi_input",
  ndi_output = "ndi_output",
  framebuffer = "framebuffer",
  framebuffer_to_texture = "framebuffer_to_texture",
  teleprompter = "teleprompter",
  text = "text",
  sinus_source = "sinus_source",
  circle_source = "circle_source",
  test_pattern = "test_pattern",
  draw_box = "draw_box",
  infinite_multiviewer = "infinite_multiviewer",
  mix_tex_2 = "mix_tex_2",
  switch_f64_4 = "switch_f64_4",
  switch_f64_8 = "switch_f64_8",
  switch_vec2_4 = "switch_vec2_4",
  switch_vec2_8 = "switch_vec2_8",
  switch_rect_4 = "switch_rect_4",
  switch_rect_8 = "switch_rect_8",
  switch_tex_4 = "switch_tex_4",
  switch_tex_8 = "switch_tex_8",
}
