# Explicit acquisition step, never an implicit configure-time download.
# cmake -DCEF_ARCHIVE=/path/sdk.tar.bz2 -DCEF_DESTINATION=/path/sdk -P acquire.cmake
cmake_minimum_required(VERSION 3.28)
if(NOT CEF_ARCHIVE OR NOT CEF_DESTINATION)
    message(FATAL_ERROR "Provide CEF_ARCHIVE (download/cache path) and CEF_DESTINATION (new SDK directory)")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/sdk.json" MANIFEST)
string(JSON URL GET "${MANIFEST}" url)
string(JSON HASH GET "${MANIFEST}" sha256)
string(JSON VERSION GET "${MANIFEST}" version)
string(JSON PLATFORM GET "${MANIFEST}" platform)
if(NOT EXISTS "${CEF_ARCHIVE}")
    file(DOWNLOAD "${URL}" "${CEF_ARCHIVE}" EXPECTED_HASH "SHA256=${HASH}" TLS_VERIFY ON SHOW_PROGRESS)
endif()
# Verify cached artifacts too.
file(SHA256 "${CEF_ARCHIVE}" ACTUAL_HASH)
if(NOT ACTUAL_HASH STREQUAL HASH)
    message(FATAL_ERROR "Cached CEF archive does not match the pinned SHA-256")
endif()
if(EXISTS "${CEF_DESTINATION}")
    message(FATAL_ERROR "CEF_DESTINATION must not already exist")
endif()
set(EXTRACT_DIRECTORY "${CEF_DESTINATION}.extract")
if(EXISTS "${EXTRACT_DIRECTORY}")
    message(FATAL_ERROR "Extraction directory already exists: ${EXTRACT_DIRECTORY}")
endif()
file(MAKE_DIRECTORY "${EXTRACT_DIRECTORY}")
file(ARCHIVE_EXTRACT INPUT "${CEF_ARCHIVE}" DESTINATION "${EXTRACT_DIRECTORY}")
file(RENAME "${EXTRACT_DIRECTORY}/cef_binary_${VERSION}_${PLATFORM}" "${CEF_DESTINATION}")
file(REMOVE_RECURSE "${EXTRACT_DIRECTORY}")
